spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/devbhumi
spring.datasource.username=root
spring.datasource.password=divyanshu10@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true







